### ISSUE TITLE
allow http calls in conditionals

### ISSUE THREAD

**Issue by w8ai** [infobloxopen/seal#74]
support this rule syntax:
```
deny to provision petstore.pet where $species.endangered{endangered=true&species=ctx.species} != nil
```

the list http call host/path would need to be defined as a resource type:
```
components:
  schemas:
    petstore.pet:
      type: object
      properties:
        species:
          type: string
...
    species.endangered:
      type: object
      x-seal-url:
         list:
           host: worldwildlife.org 
           path: /species/directory
```

rego generated:
```
resp = http.send({"method": "get", 
  "url": "https://worldwildlife.org/species/directory?endangered=true&species=<ctx.species>", 
  "header": {"Authorization": "bearer eh__REDACTED__12"},
})
...
```
